version: '3.7'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-app:latest
    container_name: python-app
    working_dir: /app
    volumes:
      - .:/app   # 把當前目錄程式碼掛進容器
    networks:
      - my-network
    ports:
      - "5001:5000"
    #env_file:
    #  - .env

networks:
  my-network:
    external: true
