version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-note-app:latest
    container_name: stock-note-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      # 資料庫連接配置 - 必須透過環境變數設定
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # Flask 配置
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    external: true
